    public enum NewLibrarySounds {
        TEST,
        THEALIEN,
        WaterDrop,
        ElecticalBuzz,
        LeverAct,
        Generator,
        Door,
        DoorClosing,
        Metal,
        Rock,
        Tile,
        Water,
        MetalRun,
        RockRun,
        TileRun,
        WaterRun,
        Steam,
        WaterDrain,
        WaterFall,
        PlatformCrash,
        Vent,
        Crunch,
        Scream,
        Crageling,
        MonsterFootSteps,
        ChaseThemeLightMotive,
        Hit,
        PlayerGrunts
    }
    public enum NewLibraryMusic {
        Theme
    }
